version: 2.1
jobs:
  build:
    docker:
      - image: circleci/node:latest
    steps:
      # Add SSH key added at CircleCI UI
      - add_ssh_keys:
          fingerprints:
            - "80:49:f1:e4:68:d9:66:15:f1:8c:a1:03:cc:06:18:7d"
      - run:
          name: Connect to remote over SSH
          command: ssh -o "StrictHostKeyChecking no" $SSH_USER@$SSH_HOST "echo "Connection established to $SSH_HOST""   
      - checkout
      - restore_cache:
          keys:
            - v1-deps-{{ checksum "package-lock.json" }}
            - v1-deps-
      - run:
          name: Install
          command: npm install
      - save_cache:
          key: v1-deps-{{ checksum "package-lock.json" }}
          paths:
            - node_modules
      - run:
          name: Build
          command: npm run build
      - run:
          name: Copy dist
          command: scp -o stricthostkeychecking=no -r dist/* $SSH_USER@$SSH_HOST:/var/www/html          